abstract class AppStrings {
  static const String token =
      "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4ZjY0ZTg1ZjEwOGEzMGM3MjlmMThhMzQ2MGEyOWUzNyIsInN1YiI6IjY1NjQ3ZmRjYTZjMTA0MDEzODJiMDg0YSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5PQTdswGr3k0OQfA6A-FOn_KuH9ndq57UQQziQlmrRA";
}
